version: '3.8'

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    # platform: linux/amd64 # for Apple chip M1
    container_name: backend-symfony
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/project
    networks:
      - network-app
  mysql:
    image: mysql:latest
    container_name: mysql-symfony
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    networks:
      - network-app
    
networks:
  network-app:
    driver: bridge
